apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: curity-admin
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`curity-admin.{{NAMESPACE}}.bluetext.localhost`)
      kind: Rule
      services:
        - name: curity-admin
          port: 80
          scheme: https
          serversTransport: curity-transport
