apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app--web-app
spec:
  ingressClassName: traefik
  rules:
    - host: web-app.$bt{{ deploy::namespace }}.bluetext.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-app--web-app
                port:
                  number: 80
