apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchbase-sync-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-sync-gateway
  template:
    metadata:
      labels:
        app: couchbase-sync-gateway
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      initContainers:
        - name: config-templater
          image: busybox:stable
          command: ['sh', '-c', 'sed "s/__NAMESPACE__/$POD_NAMESPACE/g" /config-template/config.json > /config/config.json']
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config-template
              mountPath: /config-template
            - name: config
              mountPath: /config
      containers:
        - name: couchbase-sync-gateway
          image: couchbase/sync-gateway:3.2.0-community
          imagePullPolicy: IfNotPresent
          args:
            - "-bootstrap.use_tls_server=false"
            - "/etc/sync_gateway/config.json"
          ports:
            - containerPort: 4984
              name: public
            - containerPort: 4985
              name: admin
          readinessProbe:
            httpGet:
              path: /
              port: 4984
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 12
          volumeMounts:
            - name: config
              mountPath: /etc/sync_gateway/config.json
              subPath: config.json
      volumes:
        - name: config-template
          hostPath:
            path: /var/mnt/project/config/couchbase-sync-gateway
            type: Directory
        - name: config
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-sync-gateway
spec:
  type: ClusterIP
  selector:
    app: couchbase-sync-gateway
  ports:
    - name: public
      port: 80
      targetPort: 4984
    - name: admin
      port: 4985
      targetPort: 4985
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: couchbase-sync-gateway
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: couchbase-sync-gateway.{{NAMESPACE}}.local.bluetext.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: couchbase-sync-gateway
                port:
                  number: 80
