apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchbase-edge-server--couchbase-edge-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-edge-server--couchbase-edge-server
  template:
    metadata:
      labels:
        app: couchbase-edge-server--couchbase-edge-server
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      initContainers:
        - name: config-templater
          image: busybox:stable
          command: ['sh', '-c', 'sed "s/__NAMESPACE__/$POD_NAMESPACE/g" /config-template/config.json > /config/config.json']
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config-template
              mountPath: /config-template
            - name: config
              mountPath: /config
      containers:
        - name: couchbase-edge-server--couchbase-edge-server
          image: couchbase/edge-server:latest
          command: ["couchbase-edge-server"]
          args: ["--verbose", "/etc/edge-server/config.json"]
          ports:
            - containerPort: 59840
              name: public
          readinessProbe:
            httpGet:
              path: /
              port: 59840
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 12
          volumeMounts:
            - name: config
              mountPath: /etc/edge-server/config.json
              subPath: config.json
      volumes:
        - name: config
          emptyDir: {}
