apiVersion: apps/v1
kind: Deployment
metadata:
  name: resonate
spec:
  template:
    spec:
      containers:
        - name: resonate
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath:
            path: /var/mnt/workspace/.bluetext/cache/resonate
            type: DirectoryOrCreate
