id: tigerbeetle
kind: store
name: TigerBeetle
description: Distributed financial accounting database, single-replica development cluster
use:
  tigerbeetle: [_default]
interfaces:
  - data
connection-profiles:
  data:
    interface: data
