apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flutter--flutter
spec:
  ingressClassName: traefik
  rules:
    - host: flutter.$bt{{ deploy::namespace }}.bluetext.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flutter--flutter
                port:
                  number: 80
