apiVersion: apps/v1
kind: Deployment
metadata:
  name: curity
spec:
  template:
    spec:
      containers:
        - name: curity
          imagePullPolicy: IfNotPresent
      volumes:
        - name: config-template
          hostPath:
            path: /var/mnt/system/config/curity
            type: DirectoryOrCreate
