apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: couchbase--server
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: couchbase.$bt{{ deploy::namespace }}.bluetext.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: couchbase--server
                port:
                  number: 80
