apiVersion: v1
kind: Service
metadata:
  name: couchbase
spec:
  type: ClusterIP
  selector:
    app: couchbase
  ports:
    - name: web-ui
      port: 80
      targetPort: 8091
    - name: admin
      port: 8091
      targetPort: 8091
    - name: views
      port: 8092
      targetPort: 8092
    - name: query
      port: 8093
      targetPort: 8093
    - name: search
      port: 8094
      targetPort: 8094
    - name: analytics
      port: 8095
      targetPort: 8095
    - name: data
      port: 11210
      targetPort: 11210
