apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          volumeMounts:
            - name: system
              mountPath: /app
            - name: clients
              mountPath: /clients
            - name: models
              mountPath: /models
      volumes:
        - name: system
          hostPath:
            path: /var/mnt/system/code/services/api
            type: Directory
        - name: clients
          hostPath:
            path: /var/mnt/system/code/clients
            type: Directory
        - name: models
          hostPath:
            path: /var/mnt/system/code/models
            type: DirectoryOrCreate
