apiVersion: v1
kind: Service
metadata:
  name: couchbase-sync-gateway--couchbase-sync-gateway
spec:
  type: ClusterIP
  selector:
    app: couchbase-sync-gateway--couchbase-sync-gateway
  ports:
    - name: public
      port: 80
      targetPort: 4984
    - name: admin
      port: 4985
      targetPort: 4985
