apiVersion: apps/v1
kind: Deployment
metadata:
  name: api--api
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: api--api
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
