name: Curity Identity Server
description: OAuth 2.0 and OpenID Connect Identity Server
use:
  _default: curity
interfaces:
  - oidc          # OAuth2 / OIDC endpoints (authorize, token, JWKS, userinfo)
  - admin         # admin UI + management API
connection-profiles:
  oidc:
    interface: oidc
  jwks:
    interface: oidc
  introspection:
    interface: oidc
