apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{frontend}}
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: API_URL
              value: "http://{{gateway}}"
            - name: API_HOST
              value: "{{gateway}}.{{NAMESPACE}}.bluetext.localhost"
          volumeMounts:
            - name: system
              mountPath: /app
            - name: node-modules
              mountPath: /app/node_modules
            - name: clients
              mountPath: /clients
      volumes:
        - name: system
          hostPath:
            path: /var/mnt/system/code/services/{{frontend}}
            type: Directory
        - name: node-modules
          hostPath:
            path: /var/mnt/workspace/.bluetext/cache/{{frontend}}/node_modules
            type: DirectoryOrCreate
        - name: clients
          hostPath:
            path: /var/mnt/system/code/clients
            type: Directory
