apiVersion: v1
kind: Service
metadata:
  name: kong-enterprise--kong-enterprise
spec:
  type: ClusterIP
  selector:
    app: kong-enterprise--kong-enterprise
  ports:
    - name: proxy
      port: 80
      targetPort: 8000
