apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter
  annotations:
    bluetext.io/dev-command: "./bin/dev"
    bluetext.io/dev-mode: host-forward
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flutter
  template:
    metadata:
      labels:
        app: flutter
    spec:
      containers:
        - name: app
          image: registry.k8s.io/pause:3.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: project
              mountPath: /app
      volumes:
        - name: project
          hostPath:
            path: /var/mnt/project/code/apps/flutter
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: flutter
spec:
  type: ClusterIP
  selector:
    app: flutter
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flutter
spec:
  ingressClassName: traefik
  rules:
    - host: flutter.{{NAMESPACE}}.bluetext.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flutter
                port:
                  number: 80
