apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: app
          image: oven/bun:latest
          command: ["sh", "-c", "cd /app && bun install && bun run dev --host"]
          ports:
            - containerPort: 5173
          env:
            - name: API_URL
              value: "http://traefik.kube-system.svc.cluster.local"
            - name: API_HOST
              value: "api.{{NS:api}}.bluetext.localhost"
          volumeMounts:
            - name: project
              mountPath: /app
            - name: node-modules
              mountPath: /app/node_modules
            - name: clients
              mountPath: /clients
      volumes:
        - name: project
          hostPath:
            path: /var/mnt/project/code/apps/web-app
            type: Directory
        - name: node-modules
          hostPath:
            path: /var/mnt/project/.bluetext/cache/web-app/node_modules
            type: DirectoryOrCreate
        - name: clients
          hostPath:
            path: /var/mnt/project/code/clients
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
    - port: 80
      targetPort: 5173
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app
spec:
  ingressClassName: traefik
  rules:
    - host: web-app.{{NAMESPACE}}.bluetext.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-app
                port:
                  number: 80
