id: flutter
name: Flutter App
description: Mobile app running on host emulator with host-forward dev mode
use:
  flutter: [_default]
interfaces:
  - http
connection-profiles:
  http:
    interface: http
