apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resonate
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: resonate.{{NAMESPACE}}.bluetext.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resonate
                port:
                  number: 80
