apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter
  annotations:
    bluetext.io/adb-server: "true"
spec:
  template:
    spec:
      containers:
        - name: app
          volumeMounts:
            - name: project
              mountPath: /app
            - name: pub-cache
              mountPath: /root/.pub-cache
            - name: gradle-cache
              mountPath: /root/.gradle
            - name: sdk-cache
              mountPath: /sdk-cache
      volumes:
        - name: project
          hostPath:
            path: /var/mnt/project/code/apps/flutter
            type: Directory
        - name: pub-cache
          hostPath:
            path: /var/mnt/workspace/.bluetext/cache/flutter/pub
            type: DirectoryOrCreate
        - name: gradle-cache
          hostPath:
            path: /var/mnt/workspace/.bluetext/cache/flutter/gradle
            type: DirectoryOrCreate
        - name: sdk-cache
          hostPath:
            path: /var/mnt/workspace/.bluetext/cache/flutter/sdk
            type: DirectoryOrCreate
