apiVersion: v1
kind: Service
metadata:
  name: tigerbeetle--tigerbeetle-headless
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: tigerbeetle--tigerbeetle
  ports:
    - name: cluster
      port: 3000
      targetPort: 3000
