apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-config-manager
spec:
  template:
    spec:
      containers:
        - name: service-config-manager
          volumeMounts:
            - name: system
              mountPath: /app
            - name: config
              mountPath: /config
            - name: pip-cache
              mountPath: /root/.cache
      volumes:
        - name: system
          hostPath:
            path: /var/mnt/system/code/services/service-config-manager
            type: Directory
        - name: config
          hostPath:
            path: /var/mnt/system/config
            type: Directory
        - name: pip-cache
          hostPath:
            path: /var/mnt/workspace/.bluetext/cache/service-config-manager/pip
            type: DirectoryOrCreate
