apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flutter
  template:
    metadata:
      labels:
        app: flutter
    spec:
      containers:
        - name: app
          image: bluetext-flutter:latest
          imagePullPolicy: Never
          command: ["sh", "-c", "cd /app && ./bin/init && exec ./bin/dev"]
          ports:
            - containerPort: 8080
          env:
            - name: ANDROID_ADB_SERVER_ADDRESS
              value: host.docker.internal
