id: kong-enterprise
use:
  kong-enterprise: [_default]
interfaces:
  - proxy        # data-plane: routes traffic to upstream services
  - admin        # control-plane: declarative config + plugin admin
connection-profiles:
  proxy:
    interface: proxy
  admin:
    interface: admin
